
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutUs': typeof import("../components/AboutUs.vue")['default']
    'AnimatedComponent': typeof import("../components/AnimatedComponent.vue")['default']
    'AnimatedImage': typeof import("../components/AnimatedImage.vue")['default']
    'ContactForm': typeof import("../components/ContactForm.vue")['default']
    'CorporateHousing': typeof import("../components/CorporateHousing.vue")['default']
    'FAQSection': typeof import("../components/FAQSection.vue")['default']
    'Features': typeof import("../components/Features.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'Gallery': typeof import("../components/Gallery.vue")['default']
    'GuaranteedRentInHerts': typeof import("../components/GuaranteedRentInHerts.vue")['default']
    'HeroSection': typeof import("../components/HeroSection.vue")['default']
    'HowGuaranteedRentWorks': typeof import("../components/HowGuaranteedRentWorks.vue")['default']
    'HowItWorksLandlords': typeof import("../components/HowItWorksLandlords.vue")['default']
    'HowWeWork': typeof import("../components/HowWeWork.vue")['default']
    'LandlordBenefits': typeof import("../components/LandlordBenefits.vue")['default']
    'MissionVision': typeof import("../components/MissionVision.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'Responsibilities': typeof import("../components/Responsibilities.vue")['default']
    'TemporaryAccommodation': typeof import("../components/TemporaryAccommodation.vue")['default']
    'TheProcess': typeof import("../components/TheProcess.vue")['default']
    'TradeAccommodation': typeof import("../components/TradeAccommodation.vue")['default']
    'WhyStayWithUs': typeof import("../components/WhyStayWithUs.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutUs': typeof import("../components/AboutUs.vue")['default']
    'LazyAnimatedComponent': typeof import("../components/AnimatedComponent.vue")['default']
    'LazyAnimatedImage': typeof import("../components/AnimatedImage.vue")['default']
    'LazyContactForm': typeof import("../components/ContactForm.vue")['default']
    'LazyCorporateHousing': typeof import("../components/CorporateHousing.vue")['default']
    'LazyFAQSection': typeof import("../components/FAQSection.vue")['default']
    'LazyFeatures': typeof import("../components/Features.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyGallery': typeof import("../components/Gallery.vue")['default']
    'LazyGuaranteedRentInHerts': typeof import("../components/GuaranteedRentInHerts.vue")['default']
    'LazyHeroSection': typeof import("../components/HeroSection.vue")['default']
    'LazyHowGuaranteedRentWorks': typeof import("../components/HowGuaranteedRentWorks.vue")['default']
    'LazyHowItWorksLandlords': typeof import("../components/HowItWorksLandlords.vue")['default']
    'LazyHowWeWork': typeof import("../components/HowWeWork.vue")['default']
    'LazyLandlordBenefits': typeof import("../components/LandlordBenefits.vue")['default']
    'LazyMissionVision': typeof import("../components/MissionVision.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyResponsibilities': typeof import("../components/Responsibilities.vue")['default']
    'LazyTemporaryAccommodation': typeof import("../components/TemporaryAccommodation.vue")['default']
    'LazyTheProcess': typeof import("../components/TheProcess.vue")['default']
    'LazyTradeAccommodation': typeof import("../components/TradeAccommodation.vue")['default']
    'LazyWhyStayWithUs': typeof import("../components/WhyStayWithUs.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutUs: typeof import("../components/AboutUs.vue")['default']
export const AnimatedComponent: typeof import("../components/AnimatedComponent.vue")['default']
export const AnimatedImage: typeof import("../components/AnimatedImage.vue")['default']
export const ContactForm: typeof import("../components/ContactForm.vue")['default']
export const CorporateHousing: typeof import("../components/CorporateHousing.vue")['default']
export const FAQSection: typeof import("../components/FAQSection.vue")['default']
export const Features: typeof import("../components/Features.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Gallery: typeof import("../components/Gallery.vue")['default']
export const GuaranteedRentInHerts: typeof import("../components/GuaranteedRentInHerts.vue")['default']
export const HeroSection: typeof import("../components/HeroSection.vue")['default']
export const HowGuaranteedRentWorks: typeof import("../components/HowGuaranteedRentWorks.vue")['default']
export const HowItWorksLandlords: typeof import("../components/HowItWorksLandlords.vue")['default']
export const HowWeWork: typeof import("../components/HowWeWork.vue")['default']
export const LandlordBenefits: typeof import("../components/LandlordBenefits.vue")['default']
export const MissionVision: typeof import("../components/MissionVision.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const Responsibilities: typeof import("../components/Responsibilities.vue")['default']
export const TemporaryAccommodation: typeof import("../components/TemporaryAccommodation.vue")['default']
export const TheProcess: typeof import("../components/TheProcess.vue")['default']
export const TradeAccommodation: typeof import("../components/TradeAccommodation.vue")['default']
export const WhyStayWithUs: typeof import("../components/WhyStayWithUs.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutUs: typeof import("../components/AboutUs.vue")['default']
export const LazyAnimatedComponent: typeof import("../components/AnimatedComponent.vue")['default']
export const LazyAnimatedImage: typeof import("../components/AnimatedImage.vue")['default']
export const LazyContactForm: typeof import("../components/ContactForm.vue")['default']
export const LazyCorporateHousing: typeof import("../components/CorporateHousing.vue")['default']
export const LazyFAQSection: typeof import("../components/FAQSection.vue")['default']
export const LazyFeatures: typeof import("../components/Features.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyGallery: typeof import("../components/Gallery.vue")['default']
export const LazyGuaranteedRentInHerts: typeof import("../components/GuaranteedRentInHerts.vue")['default']
export const LazyHeroSection: typeof import("../components/HeroSection.vue")['default']
export const LazyHowGuaranteedRentWorks: typeof import("../components/HowGuaranteedRentWorks.vue")['default']
export const LazyHowItWorksLandlords: typeof import("../components/HowItWorksLandlords.vue")['default']
export const LazyHowWeWork: typeof import("../components/HowWeWork.vue")['default']
export const LazyLandlordBenefits: typeof import("../components/LandlordBenefits.vue")['default']
export const LazyMissionVision: typeof import("../components/MissionVision.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyResponsibilities: typeof import("../components/Responsibilities.vue")['default']
export const LazyTemporaryAccommodation: typeof import("../components/TemporaryAccommodation.vue")['default']
export const LazyTheProcess: typeof import("../components/TheProcess.vue")['default']
export const LazyTradeAccommodation: typeof import("../components/TradeAccommodation.vue")['default']
export const LazyWhyStayWithUs: typeof import("../components/WhyStayWithUs.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
